// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdMtb7vjnQa9rdYixChFVBO7_kioJZHV4',
    appId: '1:753864698672:web:4a6c8da862c5d6a2ecf6f5',
    messagingSenderId: '753864698672',
    projectId: 'purifier-master-9dca0',
    authDomain: 'purifier-master-9dca0.firebaseapp.com',
    storageBucket: 'purifier-master-9dca0.appspot.com',
    measurementId: 'G-D5QDBP2B9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-gMNf_dne5WAuov7vODKASkGEF4GEgR4',
    appId: '1:753864698672:android:fc3a21e85ca50fa3ecf6f5',
    messagingSenderId: '753864698672',
    projectId: 'purifier-master-9dca0',
    storageBucket: 'purifier-master-9dca0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqLE8WlHfn35XEfwSsxl26QvvalMx0pyA',
    appId: '1:753864698672:ios:9078d8e1ec622a47ecf6f5',
    messagingSenderId: '753864698672',
    projectId: 'purifier-master-9dca0',
    storageBucket: 'purifier-master-9dca0.appspot.com',
    androidClientId: '753864698672-8vmv9k75vukqo6cnkqktrlu2v6vp104p.apps.googleusercontent.com',
    iosClientId: '753864698672-ht4dct05qd25nf9vl1ijvhh1btfsijje.apps.googleusercontent.com',
    iosBundleId: 'com.example.purifierMasterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqLE8WlHfn35XEfwSsxl26QvvalMx0pyA',
    appId: '1:753864698672:ios:9078d8e1ec622a47ecf6f5',
    messagingSenderId: '753864698672',
    projectId: 'purifier-master-9dca0',
    storageBucket: 'purifier-master-9dca0.appspot.com',
    androidClientId: '753864698672-8vmv9k75vukqo6cnkqktrlu2v6vp104p.apps.googleusercontent.com',
    iosClientId: '753864698672-ht4dct05qd25nf9vl1ijvhh1btfsijje.apps.googleusercontent.com',
    iosBundleId: 'com.example.purifierMasterProject',
  );
}
